### PR TITLE
Views

### PR DESCRIPTION
**Pull request by Anand8317**
- Functional view for users and specific user. (Navigation using clicking on the user)
- Functional view of user recent posts as well as user all posts
- Functional view of a specific post by specific user

### CODE REVIEW

**Review by AmaduKamara — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️ ♻️ ♻️

Hi @Anand8317,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Set up views and partials correctly 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] The app runs successfully but the user's data are not showing on the screen to make sure the views wireframe design was implemented correctly. Kindly work on that so the views are shown on the browser after users and posts are created with the `rails c` command. 👍🏽

Screenshot 2024-01-27 at 2 17 32 PM

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Anand8317** [comment]
Hey @AmaduKamara , It is showing on my laptop. The issue could be there are no users in your local database.

**Comment by Anand8317** [comment]
> Hey @AmaduKamara , It is showing on my laptop. The issue could be there are no users in your local database.

**Comment by Anand8317** [comment]
Screenshot 2024-01-27 at 8 41 24 PM

**Review by AmaduKamara — APPROVED** [review]
# Status: APPROVED 🟢 🟢 🟢

Hi @Anand8317,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights: 

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Created views correctly as expected 👍🏽
✅ Good job creating partials for users and post views 👍🏽
✅ Good communication with a reviewer 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
